# Basic Information 
title: Sunham Kim
position: Ph.D. Candidate
affiliation: Purdue University
affiliation_link: https://krannert.purdue.edu/
email: sh-kim (at) purdue.edu

# Search Engine Optimization (SEO)
keywords: sunham kim, kim sunham, sunhamkim, kimsunham, sunham, purdue, economics, econ
canonical: https://sunhamkim.github.io
description: Sunham Kim is a Ph.D. candidate at Purdue University. His research insterest includes spatial economics, international trade, macroeconomics, and human capital.

# The option is used to enable the MPI Informatics template.
enable_mpi_logo: false

# Links
# google_scholar: https://scholar.google.com/citations?user=Uf9GqRsAAAAJ
cv_link: https://sunhamkim.github.io/files/pdf/CurriculumVitae_SKim.pdf
github_link: https://github.com/sunhamkim/
linkedin: https://www.linkedin.com/in/sunhamkim/
twitter: https://twitter.com/sunham_kim/

# Images 
avatar: ./files/img/profile_1.jpg
favicon: ./assets/img/favicon.ico
favicon_dark: ./assets/img/favicon-dark.png

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my Google Analytics and ClustrMaps accounts.
google_analytics: G-3B09YM4Y7W
clustrmaps_link: //clustrmaps.com/globe.js?d=QsP-3Qm0fSNU94UxmGJF47QKd4gsH-E2IA0XQyxXREM
                   
# General Data Protection Regulation (GDPR) information
# If you don't need to add the GDPR information, you may remove the following lines.
# imprint: https://imprint.mpi-klsb.mpg.de/inf/people.mpi-inf.mpg.de/yaliu
# data_protection: https://data-protection.mpi-klsb.mpg.de/inf/people.mpi-inf.mpg.de/yaliu?lang=en

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - minimal-light.gemspec
  - CNAME
